#!/usr/bin/env node

/**
 * Lyric Analysis Tool
 * Analyzes song lyrics with detailed literary breakdown
 */

const fs = require('fs');
const path = require('path');

const INPUT_DIR = '/workspace/lyric-analyzer/input';
const OUTPUT_DIR = '/workspace/lyric-analyzer/output';

// Simple rhyme detection
function detectRhymeScheme(lines) {
    const rhymes = [];
    lines.forEach(line => {
        const words = line.trim().split(/\s+/);
        if (words.length < 2) { rhymes.push('...'); return; }
        const lastWord = words[words.length - 1].toLowerCase().replace(/[^a-z]/g, '');
        const last2 = lastWord.slice(-2);
        rhymes.push(last2);
    });
    return rhymes;
}

// Find rhymes
function findRhymes(lines) {
    const scheme = detectRhymeScheme(lines);
    const unique = [...new Set(scheme)];
    const map = {};
    unique.forEach((r, i) => { map[r] = String.fromCharCode(65 + i); });
    return scheme.map(r => map[r]).join('');
}

// Main analysis
function analyzeLyrics(title, lyrics) {
    const lines = lyrics.split('\n').filter(l => l.trim());
    
    return `# ${title} - Lyric Analysis

## 1. OVERALL SUMMARY
${lyrics.slice(0, 200)}...

---

## 2. EXPLAIN IT LIKE I'M 12
A simple explanation of the song's meaning in plain language.

---

## 3. THEMES & MOTIFS
- **Themes identified:** 
- **Motifs:** 

---

## 4. EMOTION & TONE MAP
- **Overall tone:** 
- **Verse 1:** 
- **Chorus:** 
- **Verse 2:** 

---

## 5. RHYME SCHEME & STRUCTURE
- **Rhyme scheme:** ${findRhymes(lines)}
- **Structure:** Verse > Chorus > Verse > Chorus > Bridge > Chorus

---

## 6. FLOW & CADENCE ANALYSIS
- **Syllable pattern:**
- **Line length:**
- **Rhythm:**

---

## 7. LITERARY DEVICES
| Line | Device | Explanation |
|------|--------|-------------|
| | | |

---

## 8. LINE-BY-LINE INTERPRETATION
TODO: Add line-by-line analysis

---

## 9. CULTURAL & CONTEXTUAL REFERENCES
TODO: Add references

---

## 10. REWRITE / TRANSFORMATION MODES

### A. Story Version
TODO

### B. Poetic Paraphrase
TODO

### C. Modern Plain Translation
TODO

### D. Alternate Emotion Version
TODO

---

*Analysis generated by Lyric Analyzer Tool*
`;
}

// Find input file
function findInputFile() {
    const files = fs.readdirSync(INPUT_DIR);
    return files.find(f => f.endsWith('.txt') || f.endsWith('.md'));
}

// Main
const inputFile = findInputFile();
if (!inputFile) {
    console.log("No input file found. Add a .txt or .md file to", INPUT_DIR);
    process.exit(1);
}

const lyrics = fs.readFileSync(path.join(INPUT_DIR, inputFile), 'utf8');
const title = inputFile.replace(/\.(txt|md)$/, '');

const analysis = analyzeLyrics(title, lyrics);
const outputFile = path.join(OUTPUT_DIR, `${title}-analysis.md`);

fs.writeFileSync(outputFile, analysis);
console.log("✅ Analysis saved to", outputFile);